export default {
    UNREAL: "192.168.1.124",
    MAC: "192.168.0.34",
    AUDIO: "192.168.0.99",
    BACKUP_LAPTOP: "192.168.0.100",

    ULULATIONS_OSC_MIDI: 'UlulationsOSC',
    //NOTES
    MIDI_DROPLET_LOW: 3,
    MIDI_DROPLET_MED: 2,
    MIDI_DROPLET_HIGH: 1,
    MIDI_DROPLET_GUIDING: 4,//this is with the singing voice

    MIDI_CTRL_LOW: 7,
    MIDI_CTRL_MID: 6,
    MIDI_CTRL_HIGH: 5,
    MIDI_CTRL_GUIDING: 99,

    MIDI_CTRL_BUBBLE_HIGH: 8,
    MIDI_CTRL_BUBBLE_MIDDLE: 9,
    MIDI_CTRL_BUBBLE_LOW: 10,

    MIDI_CTRL_BUBBLE_WITH_VOICE_HIGH: 11,
    MIDI_CTRL_BUBBLE_WITH_VOICE_MIDDLE: 12,
    MIDI_CTRL_BUBBLE_WITH_VOICE_LOW: 13,
    MIDI_CTRL_BUBBLE_WITH_VOICE_GUIDING: 17,

    //UNUSED!!!
    MIDI_CTRL_GUIDING_VOICE_BACKGROUND: 14,

    MIDI_MORSE_CODE_SHORT: 15,
    MIDI_MORSE_CODE_LONG: 16,

    MIDI_GUIDING_VOICE_SPLASH: 20,

    REMAP_OSC_IP: null,
    REMAP_PORT: 53021,
    REMAP_REPLY_PORT: 53022,
    REMAP_MIDI_SOMI_IN: 'SOMI-IN',
    REMAP_MIDI_OUT: 'UlulationsMIDI',

    //SOMI MAPPINGS HERE:
    SOMI_HUMAN_MIDI_CHANNEL_MAP: [5,6,7,8,9,10],
}  